# Type help("robolink") or help("robodk") for more information
# Press F5 to run the script
# Documentation: https://robodk.com/doc/en/RoboDK-API.html
# Reference:     https://robodk.com/doc/en/PythonAPI/index.html
# Note: It is not required to keep a copy of this file, your python script is saved with the station
from robolink import *    # RoboDK API
from robodk import *      # Robot toolbox
RDK = Robolink()

#Robot object creation
robot = RDK.Item("KUKA LBR iiwa 14 R820", ITEM_TYPE_ROBOT)
if not robot.Valid():
    raise Exception('Could not find robot KUKA LBR iiwa 14 R820')

#Robot frame creation
robotFrame = robot.Parent()
if robotFrame.Type() != ITEM_TYPE_FRAME:
    raise Exception('Robot parent is not a frame')



# Program Start,Prog1
def Prog1():
    # Create program item for: Prog1
    Prog1 = RDK.Item('Prog1',ITEM_TYPE_PROGRAM)
    if Prog1.Valid():
        raise Exception('Program with name Prog1 already exists.')
    Prog1 = RDK.AddProgram('Prog1')
    Prog1.setParam("Tree","collapse")

    #Program generated by RoboDK v5.9.0 for KUKA LBR iiwa 14 R820 on 05/05/2025 14:01:12
    #Using nominal kinematics.
    #Set frame Frente
    Frente = RDK.Item("Frente", ITEM_TYPE_FRAME)
    if not Frente.Valid():
        Frente = RDK.AddFrame("Frente")
        Frente.setPose(Pose(-600.000, -20.000, 405.000,  -0.000, 0.000, -0.000))
        Frente.setParent('robotFrame')
    Prog1.setPoseFrame(Frente)

    #MoveJ Pose(1240.000, -360.000, 60.000,  90.000, 10.000, -90.000)
    AutoTarget0 = RDK.AddTarget('AutoTarget 0',robotFrame,robot)
    AutoTarget0.setPose(Pose(1240.000, -360.000, 60.000,  90.000, 10.000, -90.000))
    Prog1.MoveJ([AutoTarget0],True)
    #MoveJ Pose(165.000, 690.000, 355.000,  -90.000, -40.000, 90.000)
    AutoTarget1 = RDK.AddTarget('AutoTarget 1',robotFrame,robot)
    AutoTarget1.setPose(Pose(165.000, 690.000, 355.000,  -90.000, -40.000, 90.000))
    Prog1.MoveJ([AutoTarget1],True)
    #MoveJ Pose(-5.000, 30.000, 35.000,  90.000, 20.000, -90.000)
    AutoTarget2 = RDK.AddTarget('AutoTarget 2',robotFrame,robot)
    AutoTarget2.setPose(Pose(-5.000, 30.000, 35.000,  90.000, 20.000, -90.000))
    Prog1.MoveJ([AutoTarget2],True)
    return

#Call main
Prog1()
